title: learnPage
theme: minima
author: user
email: userain.com
description: > # this means to ignore newlines until "baseurl:"
  learning

# social links
twitter_username: user
github_username:  user

show_excerpts: true # set to false to remove excerpts on the homepage
